theme: minima
title: "Eric's Awesome Blog"
author: Eric Hampton 
email: EricHampton2010@gmail.com
description: This blog will discuss many different things including Basketball, Fantasy Football, and favorite Podcasts!

# social links
twitter_username:
github_username:  EricHampton12

show_excerpts: true # set to false to remove excerpts on the homepage
