2019-08-22-Eric's-Awesome-Blog.Markup

theme: minima
title: Eric's Awesome Blog
author: Eric Hampton
email: EricHampton2010@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the blog for Eric Hampton. This site will discuss many different things including:
    - Basketball
    - Fantasy Football
    - Favorite Podcasts
    - Etc

# social links
twitter_username: @Old_Sport12
github_username:  EricHampton12

show_excerpts: true # set to false to remove excerpts on the homepage
